import {
  Star,
  Heart,
  House,
  Plus,
  Minus,
  Check,
  X,
  Search,
  Settings,
  User,
  Bell,
  Trash2,
  Pencil,
  Share,
  Camera,
  Image as ImageIcon,
  Play,
  Pause,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  ArrowRight,
  ArrowLeft,
  Mail,
  Phone,
  MapPin,
  Calendar,
  Clock,
  Lock,
  Unlock,
  Eye,
  EyeOff,
  Cloud,
  Sun,
  Moon,
  Music,
  Video,
  Folder,
  File,
  Download,
  Upload,
  Wifi,
  Battery,
  Bookmark,
  Flag,
  Tag,
  ShoppingCart,
  CreditCard,
  Gift,
  ThumbsUp,
  MessageCircle,
  Send,
  Bird,
  Circle,
  Square,
  Triangle,
  Info,
  AlertCircle,
  HelpCircle,
  type LucideIcon,
} from 'lucide-react';

// SF Symbol name -> Lucide icon. (Real SF Symbols are proprietary; this is an approximation.)
const MAP: Record<string, LucideIcon> = {
  star: Star,
  'star.fill': Star,
  heart: Heart,
  'heart.fill': Heart,
  house: House,
  'house.fill': House,
  plus: Plus,
  'plus.circle': Plus,
  'plus.circle.fill': Plus,
  minus: Minus,
  checkmark: Check,
  'checkmark.circle': Check,
  'checkmark.circle.fill': Check,
  xmark: X,
  'xmark.circle': X,
  'xmark.circle.fill': X,
  magnifyingglass: Search,
  gear: Settings,
  gearshape: Settings,
  'gearshape.fill': Settings,
  person: User,
  'person.fill': User,
  'person.circle': User,
  'person.circle.fill': User,
  bell: Bell,
  'bell.fill': Bell,
  trash: Trash2,
  'trash.fill': Trash2,
  pencil: Pencil,
  'square.and.pencil': Pencil,
  'square.and.arrow.up': Share,
  camera: Camera,
  'camera.fill': Camera,
  photo: ImageIcon,
  'photo.fill': ImageIcon,
  play: Play,
  'play.fill': Play,
  pause: Pause,
  'pause.fill': Pause,
  'chevron.right': ChevronRight,
  'chevron.left': ChevronLeft,
  'chevron.down': ChevronDown,
  'chevron.up': ChevronUp,
  'arrow.right': ArrowRight,
  'arrow.left': ArrowLeft,
  envelope: Mail,
  'envelope.fill': Mail,
  phone: Phone,
  'phone.fill': Phone,
  mappin: MapPin,
  'map.fill': MapPin,
  calendar: Calendar,
  clock: Clock,
  'clock.fill': Clock,
  lock: Lock,
  'lock.fill': Lock,
  'lock.open': Unlock,
  eye: Eye,
  'eye.fill': Eye,
  'eye.slash': EyeOff,
  cloud: Cloud,
  'cloud.fill': Cloud,
  sun: Sun,
  'sun.max': Sun,
  'sun.max.fill': Sun,
  moon: Moon,
  'moon.fill': Moon,
  music: Music,
  'music.note': Music,
  video: Video,
  'video.fill': Video,
  folder: Folder,
  'folder.fill': Folder,
  doc: File,
  'doc.fill': File,
  'arrow.down': Download,
  'arrow.up': Upload,
  wifi: Wifi,
  battery: Battery,
  'battery.100': Battery,
  bookmark: Bookmark,
  'bookmark.fill': Bookmark,
  flag: Flag,
  'flag.fill': Flag,
  tag: Tag,
  'tag.fill': Tag,
  cart: ShoppingCart,
  'cart.fill': ShoppingCart,
  creditcard: CreditCard,
  gift: Gift,
  'gift.fill': Gift,
  hand: ThumbsUp,
  'hand.thumbsup': ThumbsUp,
  'hand.thumbsup.fill': ThumbsUp,
  message: MessageCircle,
  'message.fill': MessageCircle,
  paperplane: Send,
  'paperplane.fill': Send,
  swift: Bird,
  circle: Circle,
  'circle.fill': Circle,
  square: Square,
  'square.fill': Square,
  triangle: Triangle,
  'triangle.fill': Triangle,
  info: Info,
  'info.circle': Info,
  'info.circle.fill': Info,
  'exclamationmark.triangle': AlertCircle,
  'exclamationmark.circle': AlertCircle,
  questionmark: HelpCircle,
  'questionmark.circle': HelpCircle,
};

export function lookupSymbol(name: string): { Icon: LucideIcon | null; filled: boolean } {
  const Icon = MAP[name] ?? MAP[name.replace(/\.fill$/, '')] ?? null;
  return { Icon, filled: name.endsWith('.fill') };
}
